name: Code quality checks

on:
  push:
    paths:
    - "processing_saga_nextgen/**"
    - ".github/workflows/test_plugin.yaml"
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Check-code-quality:
    runs-on: ubuntu-latest
    steps:

      - name: Get source code
        uses: actions/checkout@v4
        with:
          # To fetch tags
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "REQUIREMENTS_TESTING.txt"

      - name: Install packages
        run: |
          pip install -r REQUIREMENTS_TESTING.txt
          pip install pylint

      - name: Pylint
        run: make pylint
