name: Code quality checks

on:
  push:
    paths:
    - "processing_saga_nextgen/**"
    - ".github/workflows/test_plugin.yaml"
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  Check-code-quality:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          pip install -r REQUIREMENTS_TESTING.txt
          pip install pylint

      - name: Pylint
        run: make pylint
